# Generated by Django 5.0.6 on 2024-06-22 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_experience_keyskills_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_company_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='Company_Logos/')),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('industry', models.CharField(max_length=100)),
                ('company_status', models.BooleanField(default=False)),
                ('fk_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(choices=[('Full_Time', 'Fulltime'), ('Part_time', 'Part_time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_fields', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education_requirements', models.CharField(max_length=100)),
                ('experience_requirements', models.CharField(max_length=100)),
                ('skills_and_qualifications', models.TextField()),
                ('application_deadline', models.DateTimeField()),
                ('filled', models.BooleanField(default=False)),
                ('vacancy', models.IntegerField(default=1)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('time_posted', models.TimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('fk_company_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='latest_Resume/')),
                ('status', models.CharField(max_length=20, null=True)),
                ('fk_user_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.applicantprofile')),
                ('fk_company_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobadd')),
            ],
        ),
    ]
