# Generated by Django 5.0.6 on 2024-06-19 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_this_current_emp', models.BooleanField(default=False, null=True)),
                ('current_company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('doj', models.DateField()),
                ('current_salary', models.PositiveIntegerField()),
                ('job_profile', models.TextField()),
                ('notice_period', models.CharField(choices=[('15_Days_and_less', '15_Days_and_less'), ('1Month', '1Month'), ('2Month', '2Month'), ('3Month', '3Month'), ('MoreThan3Month', 'MoreThan3Month'), ('ServingNoticePeriod', 'ServingNoticePeriod')], max_length=50)),
                ('dol', models.DateField()),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_skills', models.CharField(max_length=100)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('PROFICIENT', 'PROFICIENT'), ('EXPERT', 'EXPERT')], max_length=100)),
                ('read', models.BooleanField(default=False, null=True)),
                ('write', models.BooleanField(default=False, null=True)),
                ('speak', models.BooleanField(default=False, null=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
